### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [nav9/WalkingRobot2D#2]
Hello, I would like to confirm what license is this project released under ? I would like to study it to learn how I might use Pymunk for a reinforcement learning environment. Thank you.

**Comment by nav9** [comment]
Thank you for your interest in the code and thank you for asking for a clarification. There are a few things I want to mention:
**1. Easier way to get started:** You may run into a lot of errors when trying to run this code, because I remember the PyMumk author had introduced stricter test cases to check for movement anomalies after I pointed out some bugs to him. So when starting off, it'd help to try [this code](https://stackoverflow.com/questions/55302406/how-to-rotate-pymunk-joints-at-will), and [this code](https://github.com/nav9/LeggedRobotPyMunk) (not sure if I made the necessary changes here, but it'll be easier for you to figure out since there's lesser code).  
**2. Reinforcement learning complexity:** My project uses evolutionary learning algorithms. I had tried using reinforcement learning via neural networks too (in a different project), but the sheer number of permutations of the number of contact points of objects and the angles at which they make contact, becomes a processing bottleneck for a Python program. It can overwhelm a simple neural network. To account for such large amounts of data and to be able to train the network based on backpropagation, you'll need a very large network. You'd also have to restrict the angle of motion of the joints of the robot to minimize the number of permutations of motion possibilities. These are a bit difficult to achieve in PyMunk, so I'd suggest also considering any RoS-based robot simulator like Gazebo or physics libraries that are based on C++ or anything faster than Python (even though PyMunk is just a wrapper over Chipmunk).  
**3. Copyright:** I used this code for a research paper which I eventually published with Springer. The copyright of the paper, including any figures, tables and content directly published in the proceedings is owned by Springer. Although I don't remember the code being part of the copyright (I'll have to check the copyright agreement), it's better to be on the safer side and ensure that you don't redistribute it and don't use the code for your own project(s). I have no objection toward you running the code on your computer and studying it or tweaking it as part of your learning. I recommend downloading the entire code right now, since I plan to make this project private in a few days time, just to be on the safer side. 
  
If there's anything else you'd like to ask or mention, please feel free to contact me at navinipe@gmail.com.

**Comment by suprafun** [comment]
Thank you so very much for your advice. I will very carefully consider what you said. Thank you again for your help.
